name = "CGAL"
uuid = "2e53bf74-78a3-5519-af78-2b9094e29e3e"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com>"]
version = "0.1.1"

[deps]
Cxx = "a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
